version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "00:00"
  open-pull-requests-limit: 99
  reviewers:
  - danirod
  assignees:
  - danirod
  labels:
  - dependencies
  ignore:
  - dependency-name: "@types/node"
    versions:
    - ">= 11.a, < 12"
  - dependency-name: "@types/node"
    versions:
    - ">= 13.a, < 14"
  - dependency-name: "@types/node"
    versions:
    - "> 14.0.1, < 15"
  - dependency-name: "@types/node"
    versions:
    - 15.0.0
    - 15.0.1
  - dependency-name: sinon
    versions:
    - 10.0.1
  - dependency-name: xdg-basedir
    versions:
    - 5.0.1
  - dependency-name: husky
    versions:
    - 5.0.9
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: chai
    versions:
    - 4.3.1
    - 4.3.2
  - dependency-name: typescript
    versions:
    - 4.2.2
  - dependency-name: sqlite3
    versions:
    - 5.0.1
  - dependency-name: discord.js-commando
    versions:
    - 0.11.1
    - 0.12.0
  commit-message:
    prefix: chore
    include: scope
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "00:00"
  open-pull-requests-limit: 99
  reviewers:
  - danirod
  assignees:
  - danirod
  labels:
  - dependencies
  ignore:
  - dependency-name: node
    versions:
    - ">= 13.pre.alpine.a, < 14"
  - dependency-name: node
    versions:
    - ">= 15.pre.alpine.a, < 16"
  commit-message:
    prefix: chore
    include: scope
